# Tensorflow Basics

Created by:
### **[Prashant Brahmbhatt](www.linkedin.com/in/prashantbrahmbhatt)  **  

[GitHub](www.github.com/hashbanger)

references: JM Portilla

In [2]:
import tensorflow as tf

In [28]:
#checking the version 
print(tf.__version__)

1.7.0


## Tensors

Tensors are similar to numpy arrays

In [29]:
hello = tf.constant('hello')

In [30]:
hello

<tf.Tensor 'Const_6:0' shape=() dtype=string>

In [31]:
type(hello)

tensorflow.python.framework.ops.Tensor

A tensor must be executed within a tensorflow session.

In [32]:
sess = tf.Session()

In [33]:
sess.run(hello)

b'hello'

here a **b** indicates that the literal should become a bytes literal in Python 3

In [34]:
world = tf.constant('world')

In [35]:
result = hello + world

In [36]:
type(result)

tensorflow.python.framework.ops.Tensor

In [37]:
with tf.Session() as sess:
    result = sess.run(hello + world)

**with** begins and closes session automatically

In [38]:
result

b'helloworld'

### Computations 

In [84]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [85]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [86]:
tensor_1 + tensor_2

<tf.Tensor 'add_19:0' shape=() dtype=int32>

In [87]:
sess

In [82]:
sess = tf.Session()
sess.run(tensor_1 + tensor_2)

3

In [83]:
sess.close()

## Operations

In [47]:
const = tf.constant(10)

In [48]:
mat = tf.fill((4,4), 5)

In [49]:
mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [50]:
zeroes = tf.zeros((4,4))

In [51]:
ones = tf.ones((4,4))

In [52]:
n_dist = tf.random_normal((4,4), mean = 0, stddev= 1)

In [53]:
u_dist = tf.random_uniform((4,4), minval= 0, maxval= 1)

In [54]:
operations = [const, zeroes, ones, n_dist, u_dist]

## Interactive Session

**Interactive session** keeps a session in run and only useful for notebook purposes.

In [105]:
sess = tf.InteractiveSession()

In [106]:
operations

[<tf.Tensor 'Const_10:0' shape=() dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]

In [107]:
for op in operations:
    print("\n")
    print(op.eval())



10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.1506854  -0.9224573   1.969989   -0.8856357 ]
 [-1.3348281  -1.1988918   0.20795824  0.2684076 ]
 [-1.4153717   0.70794106 -2.0529406   0.10307066]
 [-0.22629556 -0.32520562 -0.43645534  1.0054986 ]]


[[0.55693865 0.26848447 0.00384665 0.61424565]
 [0.34940243 0.20744228 0.7963017  0.13429558]
 [0.90754604 0.8200402  0.26528668 0.7427472 ]
 [0.04484332 0.3461659  0.9460231  0.60414505]]


### Matrix Multiplication

In [108]:
mat_1 = tf.constant([[1,4],[5,3]])

In [109]:
mat_2 = tf.constant([[2],[3]])

In [110]:
mat_1.shape

TensorShape([Dimension(2), Dimension(2)])

In [111]:
mat_2.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_21:0' shape=(2, 1) dtype=int32>>

In [112]:
mat_2.shape

TensorShape([Dimension(2), Dimension(1)])

In [113]:
result = tf.matmul(mat_1, mat_2)

In [114]:
result.eval()

array([[14],
       [19]])

In [115]:
sess.run(result)

array([[14],
       [19]])

### Voila!