# Introduction to Tensorflow Eager API

By - [Prashant Brahmbhatt](www.github.com/hashbanger)  
Reference - [Tensorflow Documentation](https://www.tensorflow.org/guide/eager)

_______

The Eager API is one of the High Level tensorflow APIs like Keras.

TensorFlow's eager execution is an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computational graph to run later. This makes it easy to get started with TensorFlow and debug models, and it reduces boilerplate as well

There are three characteristics of the Eager API  
- Allows the natural structuring of code and use of python datastructures.  
- Can use python debugginh tools to for immediate error reporting  
- Simplifies the dynamic model by using the python flow of control rather than the graph like flow.

## Basic Usage

We add the eager execution at the beginning of the console

In [1]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf
tf.enable_eager_execution()

This will cause the tensorflow operations to execute immediately

In [2]:
tf.executing_eagerly()

True

In [3]:
x = tf.constant(10)
print(x)

tf.Tensor(10, shape=(), dtype=int32)


In [4]:
x = [[2]]
y = [[4]]
print(tf.matmul(x,y))

tf.Tensor([[8]], shape=(1, 1), dtype=int32)


These would not have been the results without the eager API

Now because of the eager execution **tf.Tensor** objects reference concrete values instead of symbolic handles to nodes in a computational graph. Now since there is no computational graph to run, the debugging becomes easy.

TensorFlow math operations convert Python objects and NumPy arrays to tf.Tensor objects. The tf.Tensor.numpy method returns the object's value as a NumPy ndarray.

In [5]:
a = tf.constant([[1,2],[3,2]])
print(a)

tf.Tensor(
[[1 2]
 [3 2]], shape=(2, 2), dtype=int32)


In [6]:
#Broadcasting support 
b = tf.add(1,a)
print(b)

tf.Tensor(
[[2 3]
 [4 3]], shape=(2, 2), dtype=int32)


In [7]:
a * b #element wise multiplication

<tf.Tensor: id=12, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12,  6]])>

The tf.contrib.eager module contains symbols available to both eager and graph execution environments and is useful for writing code to work with graphs

We can also get a **numPy** value from a tensor using the **.numpy()** function

In [8]:
c = tf.constant([[2,1],[5,6]])
print(c)

tf.Tensor(
[[2 1]
 [5 6]], shape=(2, 2), dtype=int32)


In [9]:
c = tf.convert_to_tensor(c).numpy()
print(c)

[[2 1]
 [5 6]]


In [10]:
type(c)

numpy.ndarray

## Dynamic Control Flow

In [11]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num.numpy())
    counter += 1


In [12]:
fizzbuzz(30)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz


This has conditionals that depend on tensor values and it prints these values at runtime.

Refer to documentation for more details.

### de nada!